name: Run Tests

on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build website
        run: |
          python main.py

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{secrets.PORT}}

      - name:
          install ssh keys
          # check this thread to understand why its needed:
          # https://stackoverflow.com/a/70447517
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_IP }} "cd ~/home/farm && git checkout main && git pull && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
